/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    {
      type: "category",
      label: "Introduction",
      items: ["introduction/introduction.md", "introduction/about-ctop", "introduction/about-iiith-scll"],
    },
    {
      type: "category",
      label: "Getting Started",
      items: ["getting-started/overview", "getting-started/prerequisites"],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        "architecture/high-level-architecture",
        "architecture/component-details",
      ],
    },
    {
      type: "category",
      label: "Functional Requirements (FRS)",
      items: [
        "functional-requirements/core-features",
        "functional-requirements/user-scenarios",
      ],
    },
    {
      type: "category",
      label: "Non-Functional Requirements (NFRS)",
      items: [
        "non-functional-requirements/performance",
        "non-functional-requirements/scalability",
        "non-functional-requirements/security",
      ],
    },
    {
      type: "category",
      label: "Load Tests",
      items: [
        "load-tests/test-environment-setup",
        "load-tests/test-results-and-analysis",
      ],
    },
    {
      type: "category",
      label: "Installation and Deployment",
      items: [
        "installation-deployment/installation-guide",
        "installation-deployment/deployment-guide",
      ],
    },
    {
      type: "category",
      label: "Development Guide",
      items: [
        "development-guide/setup-development-environment",
        "development-guide/development-workflow",
        "development-guide/building-and-testing",
      ],
    },
    {
      type: "category",
      label: "API Documentation",
      items: [
        "api-documentation/api-overview",
        "api-documentation/endpoint-descriptions",
      ],
    },
    {
      type: "category",
      label: "FAQs",
      items: ["faqs/general-faqs", "faqs/technical-faqs"],
    },
    {
      type: "category",
      label: "Contributing",
      items: [
        "contributing/how-to-contribute",
        "contributing/community-and-support",
      ],
    },
    {
      type: "category",
      label: "Change Log",
      items: ["change-log/version-history"],
    },
    {
      type: "category",
      label: "Contact Information",
      items: [
        "contact-information/team-contacts",
        "contact-information/acknowledgements",
      ],
    },
  ],
};

export default sidebars;
